spring:
  sql:
    init:
      mode: always # TODO 로컬 개발 완료시에는 제거해야함

mysql:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/timedeal
    username: user
    password: '1234'